### PR TITLE
fix(planning): populate headline using event name

### PR DESCRIPTION
**Pull request by petrjasek**
when creating planning item for an event.

### CODE REVIEW

**Comment by MarkLark86** [comment]
There is a function that we use for this called `createPlanningFromEvent` in the file `client/actions/agenda.js:217`.

Ideally this function should use the `planning_types` to populate the new Planning item from the Event.

**Comment by petrjasek** [comment]
imo such logic is better done on the server, when there will be mobile client or something it would have to duplicate it. so what about moving it there?

**Comment by mdhaman** [comment]
agree with you, we need an endpoint to create item from `planning_types`.

**Comment by petrjasek** [comment]
using `planning_type` now to check if headline is enabled

**Pull request merged**
