### PR TITLE
use timezone info when checking embargoed time from onclusive

### PR DESCRIPTION
**Pull request by petrjasek**
CPNHUB-212

### CODE REVIEW

**Review by MarkLark86 — APPROVED** [review]

**Comment by MarkLark86** [comment]
@petrjasek We're mandating here that `embargoTime` and `timezone.timezoneOffset` are both required, is there ever a case when Onclusive will provide only `embargoTime` without a UTC offset?

**Comment by MarkLark86** [comment]
Merging from `develop` should fix the tests

**Comment by petrjasek** [comment]
> @petrjasek We're mandating here that `embargoTime` and `timezone.timezoneOffset` are both required, is there ever a case when Onclusive will provide only `embargoTime` without a UTC offset?

yep that's what they confirmed

> Merging from `develop` should fix the tests

is there anything that shouldn't make it to the 2.6.1 release?

**Comment by MarkLark86** [comment]
> > @petrjasek We're mandating here that `embargoTime` and `timezone.timezoneOffset` are both required, is there ever a case when Onclusive will provide only `embargoTime` without a UTC offset?
> 
> yep that's what they confirmed
> 
> > Merging from `develop` should fix the tests
> 
> is there anything that shouldn't make it to the 2.6.1 release?

All good then. Sorry, I was incorrect, rebase against the hotfix/2.6.1 branch and will fix failing test

**Pull request merged**
