### PR TITLE
Port coverage changes

### PR DESCRIPTION
**Pull request by thecalcc**
SDESK-7361

### CODE REVIEW

**Comment by MarkLark86** [comment]
@thecalcc Is this meant for the `develop` branch or `release/2.7`?

**Comment by thecalcc** [comment]
> @thecalcc Is this meant for the `develop` branch or `release/2.7`?

Thanks Mark, it is for release/2.7

**Comment by tomaskikutis** [comment]
did you simply cherry pick or were there some conflicts?

**Comment by thecalcc** [comment]
> did you simply cherry pick or were there some conflicts?

I cherry picked

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
