### PR TITLE
use shared code style

### PR DESCRIPTION
**Pull request by petrjasek**
I've put the eslint config into another repo, let me know if the rules are ok or you would prefer some changes first, then will start fixing the code.

https://github.com/superdesk/superdesk-client-code-style

### CODE REVIEW

**Comment by mdhaman** [comment]
@petrjasek rules are fine. Can we have semi and indentation as warnings for now?

**Comment by petrjasek** [comment]
I think these are fixable automatically, but will check

**Comment by mdhaman** [comment]
yep. it automatically fixable.

**Comment by mdhaman** [comment]
@petrjasek we can close this PR. I have cherry picked your changes.

**Pull request closed without merging**
