### PR TITLE
Authoring react post broadcasting

### PR DESCRIPTION
**Pull request by tomaskikutis**
This fixes unit/e2e tests and also updates usages of superdesk-api and other imports

### CODE REVIEW

**Comment by tomaskikutis** [comment]
@petrjasek can you check the backend issue and review this?

**Comment by petrjasek** [comment]
what backend issue @tomaskikutis ?

**Comment by devketanpro** [comment]
> what backend issue @tomaskikutis ?

some test cases were failing, but when I restarted the server check, they passed!

**Comment by tomaskikutis** [comment]
yep, I was referring to nose tests failing

**Review by petrjasek — APPROVED** [review]

**Comment by petrjasek** [comment]
but seems like this wouldn't build still:
```sh
ERROR in ../planning/node_modules/redux/dist/redux.legacy-esm.js
Module parse failed: Unexpected token (376:6)
You may need an appropriate loader to handle this file type.
|     dispatch = compose(...chain)(store.dispatch);
|     return {
|       ...store,
|       dispatch
|     };
 @ ../planning/client/utils/index.ts 53:14-30
 @ ../planning/client/controllers/FulfilAssignmentController.tsx
 @ ../planning/client/controllers/index.ts
 @ ../planning/index.ts
 @ ./dist/app-importer.generated.js
 @ ./node_modules/superdesk-core/scripts/index.ts
 @ multi ./node_modules/superdesk-core/scripts/index
```

**Comment by tomaskikutis** [comment]
did you regenerate package lock from scratch @petrjasek ? Pytest is failing again now

**Pull request merged**
